### ISSUE TITLE
How to store changes ready for commit

### ISSUE THREAD

**Issue by mattdmem** [sch-sdgs/PanelPal#3]
Say I want to delete a gene, how do I store that I want to delete a gene and not actually do it - this would prevent versioning increasing on every delete gene.

**Comment by grovesn** [comment]
If we don't increase the current version of the panel after any of the commits but have a save/release button that then increases it so the new bed will be exported for analysis. 
We could add a field in the panels table to indicate if there is a new version under development and then notify the user that they can view the current version or the one in progress.
