### ISSUE TITLE
What happens if a transcript is in the refflat file twice?

### ISSUE THREAD

**Issue by grovesn** [sch-sdgs/PanelPal#5]
SMN1    NM_000344       chr5    +       69345349        69373418        69345512        69372398
SMN1    NM_000344       chr5    +       70220767        70248838        70220930        70247818

Currently only using the first one in the file - not necessarily the correct one. Need to adjust refflat import to deal with these situations.

**Comment by mattdmem** [comment]
Problem when importing is due to cds start and cds end being stored with the transcript and in the case of SMN1 and SMN2 the transcript has the same name but different cds starts and ends.
